In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset=pd.read_csv('/Data.csv')

In [0]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,3].values

In [71]:
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [0]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imp=imp.fit(X[:,1:3])
X[:,1:3]=imp.transform(X[:,1:3])


In [73]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [0]:
#ENCODING DATA CATEGORICAL

In [0]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [0]:
label_encoderX=LabelEncoder()
X[:,0]=label_encoderX.fit_transform(X[:,0])
from sklearn.compose import ColumnTransformer
onehotencoder = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)


In [0]:
X = onehotencoder.fit_transform(X)

In [79]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [80]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [0]:
#SPLLITING TRAIN AND TEST DATASET

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [83]:
X_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 61000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0]], dtype=object)

In [84]:
X_test

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [0]:
# Feature Scaling-Mean Normalisation

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc_X=StandardScaler()

In [0]:
X_train=sc_X.fit_transform(X_train)

In [0]:
X_test=sc_X.transform(X_test)

In [91]:
X_train

array([[ 1.        , -0.57735027, -0.57735027, -0.73279795, -0.58321184],
       [ 1.        , -0.57735027, -0.57735027,  1.02591713,  1.04978132],
       [ 1.        , -0.57735027, -0.57735027,  1.80756828,  1.8662779 ],
       [-1.        ,  1.73205081, -0.57735027, -1.70986189, -1.04978132],
       [ 1.        , -0.57735027, -0.57735027, -0.34197238,  0.46656947],
       [-1.        ,  1.73205081, -0.57735027,  0.24426598, -0.23328474],
       [-1.        , -0.57735027,  1.73205081, -0.14655959, -0.23328474],
       [-1.        , -0.57735027,  1.73205081, -0.14655959, -1.28306606]])

In [92]:
X_test

array([[-1.        ,  1.73205081, -0.57735027,  2.19839386,  2.33284737],
       [-1.        , -0.57735027,  1.73205081, -2.29610025, -1.74963553]])